import {Inter} from 'next/font/google';
import './globals.css';
import Navpage from '@/components/navpg';

const inter = Inter ({subsets: ['latin']});

export const metadata = {
  title: 'SwaEngTranX.',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navpage />
        {children}

      </body>
    </html>
  );
}
